overrides:
  ceph:
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
    flavor: crimson
  workunit:
    env:
      CRIMSON_COMPAT: '1'
